SET DEFINE OFF;
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('30', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYNYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('1', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYYYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('2', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYYYN', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('3', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYYNY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('4', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYNYYN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('5', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYNYN', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('6', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYNYNY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('7', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYNNY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('8', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YYYYNN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('9', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNYYYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('10', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNNYYY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('11', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNYNYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('12', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNNNYY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('13', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNYYYN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('14', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNYYNY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('15', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'YNYYNN', '4', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('16', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYYYYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('17', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYYYYN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('18', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYYYNY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('19', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYYYNN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('20', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYNNYY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('21', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYNYYN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('22', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'PERSON', 'NYYNNY', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,GENDER,DOB,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('23', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'CORPORATION', 'YYYY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('24', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'CORPORATION', 'YYNY', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('25', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'CORPORATION', 'YYYN', '1', 
    '2', 'IDENTIFIER,NAME BLOCK,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('26', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'CORPORATION', 'YYNN', '2', 
    '2', 'IDENTIFIER,NAME BLOCK,ADDRESS BLOCK,PHONE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('27', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'ADDRESS', 'YYYYYYYY', '1', 
    '2', 'LINE_ONE,LINE_TWO,LINE_THREE,LINE_FOUR,STREET_NAME,CITY,COUNTRY,POSTAL_CODE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('28', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'ADDRESS', 'YYYYYYYN', '1', 
    '2', 'LINE_ONE,LINE_TWO,LINE_THREE,LINE_FOUR,STREET_NAME,CITY,COUNTRY,POSTAL_CODE');
Insert into YUG_MSP.REF_MATCH_SCORE
   (ID_PK, VERSION, CREATED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, MATCH_ENTITY_OBJECT_NAME, MATCH_ATTR_PATTERN, MATCH_RESULT_REFKEY, MATCH_PROPOSED_ACTION_REFKEY, MATCH_ATTR_PATTERN_DESCR)
 Values
   ('29', 0, TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_TIMESTAMP('10/30/2017 5:27:23.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'admin', '00000000', 'ADDRESS', 'YYYYYNYY', '1', 
    '2', 'LINE_ONE,LINE_TWO,LINE_THREE,LINE_FOUR,STREET_NAME,CITY,COUNTRY,POSTAL_CODE');
COMMIT;
