set lines 1000;
set pages 2000;
set scan off;
set serveroutput on;

spool 'CreateTablespaces.log'
-----------------------------------------------------------------------

CREATE TABLESPACE MDM_DATATS DATAFILE 
  'D:\software\eclipse\OracleXE112_Win32\oraclexe\app\oracle\oradata\XE\MDM_DATATS.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE MDM_INDXTS DATAFILE 
  'D:\software\eclipse\OracleXE112_Win32\oraclexe\app\oracle\oradata\XE\MDM_INDXTS.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE PROFILE MDM_PROFILE LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME UNLIMITED
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS DEFAULT
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME 1
  PASSWORD_REUSE_MAX 12
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION DEFAULT;



CREATE USER MDM_OWNER
  IDENTIFIED BY mdm_owner
  DEFAULT TABLESPACE MDM_DATATS
  TEMPORARY TABLESPACE TEMP
  PROFILE MDM_PROFILE
  ACCOUNT UNLOCK;
  -- 7 Roles for MDM_OWNER 
  GRANT CONNECT TO MDM_OWNER;
  GRANT SELECT_CATALOG_ROLE TO MDM_OWNER;
  GRANT EXECUTE_CATALOG_ROLE TO MDM_OWNER;
  GRANT IMP_FULL_DATABASE TO MDM_OWNER;
  GRANT HS_ADMIN_ROLE TO MDM_OWNER;
  GRANT RESOURCE TO MDM_OWNER;
  ALTER USER MDM_OWNER DEFAULT ROLE ALL;
  -- 82 System Privileges for MDM_OWNER 
  GRANT CREATE ANY SQL PROFILE TO MDM_OWNER;
  GRANT DROP ANY SQL PROFILE TO MDM_OWNER;
  GRANT DROP ANY CONTEXT TO MDM_OWNER;
  GRANT CREATE ANY DIMENSION TO MDM_OWNER;
  GRANT CREATE ANY MATERIALIZED VIEW TO MDM_OWNER;
  GRANT CREATE ANY TRIGGER TO MDM_OWNER;
  GRANT CREATE ROLE TO MDM_OWNER;
  GRANT CREATE ANY VIEW TO MDM_OWNER;
  GRANT DROP PUBLIC SYNONYM TO MDM_OWNER;
  GRANT CREATE ANY SYNONYM TO MDM_OWNER;
  GRANT CREATE CLUSTER TO MDM_OWNER;
  GRANT INSERT ANY TABLE TO MDM_OWNER;
  GRANT DROP ANY TABLE TO MDM_OWNER;
  GRANT DROP ROLLBACK SEGMENT TO MDM_OWNER;
  GRANT DEBUG CONNECT SESSION TO MDM_OWNER;
  GRANT SELECT ANY DICTIONARY TO MDM_OWNER;
  GRANT DROP ANY OUTLINE TO MDM_OWNER;
  GRANT CREATE INDEXTYPE TO MDM_OWNER;
  GRANT DROP ANY OPERATOR TO MDM_OWNER;
  GRANT CREATE ANY OPERATOR TO MDM_OWNER;
  GRANT ALTER ANY TYPE TO MDM_OWNER;
  GRANT DROP ANY MATERIALIZED VIEW TO MDM_OWNER;
  GRANT ANALYZE ANY TO MDM_OWNER;
  GRANT CREATE TRIGGER TO MDM_OWNER;
  GRANT AUDIT ANY TO MDM_OWNER;
  GRANT CREATE ANY CONTEXT TO MDM_OWNER;
  GRANT ALTER ANY TRIGGER TO MDM_OWNER;
  GRANT EXECUTE ANY PROCEDURE TO MDM_OWNER;
  GRANT ALTER ANY PROCEDURE TO MDM_OWNER;
  GRANT CREATE PROCEDURE TO MDM_OWNER;
  GRANT CREATE DATABASE LINK TO MDM_OWNER;
  GRANT CREATE VIEW TO MDM_OWNER;
  GRANT DROP ANY INDEX TO MDM_OWNER;
  GRANT CREATE ANY INDEX TO MDM_OWNER;
  GRANT CREATE ANY CLUSTER TO MDM_OWNER;
  GRANT UPDATE ANY TABLE TO MDM_OWNER;
  GRANT EXECUTE ANY TYPE TO MDM_OWNER;
  GRANT CREATE ANY TYPE TO MDM_OWNER;
  GRANT CREATE MATERIALIZED VIEW TO MDM_OWNER;
  GRANT DROP ANY ROLE TO MDM_OWNER;
  GRANT DROP ANY SEQUENCE TO MDM_OWNER;
  GRANT DROP ANY VIEW TO MDM_OWNER;
  GRANT DROP ANY CLUSTER TO MDM_OWNER;
  GRANT DROP PUBLIC DATABASE LINK TO MDM_OWNER;
  GRANT CREATE PUBLIC DATABASE LINK TO MDM_OWNER;
  GRANT CREATE ANY SEQUENCE TO MDM_OWNER;
  GRANT CREATE ANY TABLE TO MDM_OWNER;
  GRANT BECOME USER TO MDM_OWNER;
  GRANT UNLIMITED TABLESPACE TO MDM_OWNER;
  GRANT DROP TABLESPACE TO MDM_OWNER;
  GRANT ALTER SESSION TO MDM_OWNER;
  GRANT CREATE ANY INDEXTYPE TO MDM_OWNER;
  GRANT CREATE ANY LIBRARY TO MDM_OWNER;
  GRANT CREATE TYPE TO MDM_OWNER;
  GRANT CREATE PROFILE TO MDM_OWNER;
  GRANT CREATE SEQUENCE TO MDM_OWNER;
  GRANT DROP ANY DIMENSION TO MDM_OWNER;
  GRANT GLOBAL QUERY REWRITE TO MDM_OWNER;
  GRANT CREATE OPERATOR TO MDM_OWNER;
  GRANT DROP ANY LIBRARY TO MDM_OWNER;
  GRANT DROP ANY TYPE TO MDM_OWNER;
  GRANT DROP ANY DIRECTORY TO MDM_OWNER;
  GRANT DROP ANY TRIGGER TO MDM_OWNER;
  GRANT CREATE ANY PROCEDURE TO MDM_OWNER;
  GRANT COMMENT ANY TABLE TO MDM_OWNER;
  GRANT ALTER ANY TABLE TO MDM_OWNER;
  GRANT CREATE TABLE TO MDM_OWNER;
  GRANT DROP USER TO MDM_OWNER;
  GRANT CREATE USER TO MDM_OWNER;
  GRANT CREATE TABLESPACE TO MDM_OWNER;
  GRANT RESUMABLE TO MDM_OWNER;
  GRANT ADMINISTER DATABASE TRIGGER TO MDM_OWNER;
  GRANT DROP ANY INDEXTYPE TO MDM_OWNER;
  GRANT CREATE ANY DIRECTORY TO MDM_OWNER;
  GRANT DROP PROFILE TO MDM_OWNER;
  GRANT DROP ANY PROCEDURE TO MDM_OWNER;
  GRANT CREATE PUBLIC SYNONYM TO MDM_OWNER;
  GRANT DROP ANY SYNONYM TO MDM_OWNER;
  GRANT CREATE SYNONYM TO MDM_OWNER;
  GRANT SELECT ANY TABLE TO MDM_OWNER;
  GRANT CREATE ROLLBACK SEGMENT TO MDM_OWNER;
  GRANT CREATE SESSION TO MDM_OWNER;
  -- 3 Tablespace Quotas for MDM_OWNER 
  ALTER USER MDM_OWNER QUOTA UNLIMITED ON MDM_DATATS;
  ALTER USER MDM_OWNER QUOTA UNLIMITED ON MDM_INDXTS;
