set lines 1000;
set pages 2000;
set scan off;
set serveroutput on;

alter session set NLS_DATE_LANGUAGE='AMERICAN';
spool 'LoadTableDataWrapper.log'
-----------------------------------------------------------------------
Select 'ACCOUNT' from DUAL;
@.\DataImport\ACCOUNT.sql
Select 'AL_AUTH_USER_REGISTRY' from DUAL;
@.\DataImport\AL_AUTH_USER_REGISTRY.sql
Select 'AL_CONFIG_APP_PROPERTIES' from DUAL;
@.\DataImport\AL_CONFIG_APP_PROPERTIES.sql
Select 'AL_CORPORATIONNAMES' from DUAL;
@.\DataImport\AL_CORPORATIONNAMES.sql
Select 'AL_MISCELLANEOUS_INFO' from DUAL;
@.\DataImport\AL_MISCELLANEOUS_INFO.sql
Select 'AL_REF_CLASSIFICATION_CODE' from DUAL;
@.\DataImport\AL_REF_CLASSIFICATION_CODE.sql
Select 'AL_REF_HIGHEST_EDU_QUAL' from DUAL;
@.\DataImport\AL_REF_HIGHEST_EDU_QUAL.sql
Select 'AL_REF_IMPORTANCE_TYPE' from DUAL;
@.\DataImport\AL_REF_IMPORTANCE_TYPE.sql
Select 'AL_REF_INDUSTRY_CODE' from DUAL;
@.\DataImport\AL_REF_INDUSTRY_CODE.sql
Select 'AL_REF_PHONE_TYPE' from DUAL;
@.\DataImport\AL_REF_PHONE_TYPE.sql
Select 'AL_REF_RELATIONSHIP_STATUS' from DUAL;
@.\DataImport\AL_REF_RELATIONSHIP_STATUS.sql
Select 'AUTH_ROLES_REGISTRY' from DUAL;
@.\DataImport\AUTH_ROLES_REGISTRY.sql
Select 'LE_CORPORATION' from DUAL;
@.\DataImport\LE_CORPORATION.sql
Select 'LE_PERSON' from DUAL;
@.\DataImport\LE_PERSON.sql
Select 'REF_BATCH_ACTION_STATUS' from DUAL;
@.\DataImport\REF_BATCH_ACTION_STATUS.sql
Select 'REF_BRANCH_CODE' from DUAL;
@.\DataImport\REF_BRANCH_CODE.sql
Select 'REF_COUNTRY_ISO' from DUAL;
@.\DataImport\REF_COUNTRY_ISO.sql
Select 'REF_DEACTIVATION_REASON' from DUAL;
@.\DataImport\REF_DEACTIVATION_REASON.sql
Select 'REF_IMPORTANCE_TYPE' from DUAL;
@.\DataImport\REF_IMPORTANCE_TYPE.sql
Select 'REF_MATCH_RESULT' from DUAL;
@.\DataImport\REF_MATCH_RESULT.sql
Select 'REF_PROPERTY_LE_RELTYPE' from DUAL;
@.\DataImport\REF_PROPERTY_LE_RELTYPE.sql
Select 'REF_SUFFIX_NAME' from DUAL;
@.\DataImport\REF_SUFFIX_NAME.sql
Select 'AL_CONFIG_INQUIRY_LEVELS' from DUAL;
@.\DataImport\AL_CONFIG_INQUIRY_LEVELS.sql
Select 'AL_ENTITY_GROUP' from DUAL;
@.\DataImport\AL_ENTITY_GROUP.sql
Select 'AL_LE_CORPORATION' from DUAL;
@.\DataImport\AL_LE_CORPORATION.sql
Select 'AL_LE_PHONE_ASSOC' from DUAL;
@.\DataImport\AL_LE_PHONE_ASSOC.sql
Select 'AL_REF_ENTITY_OBJECT_TYPE' from DUAL;
@.\DataImport\AL_REF_ENTITY_OBJECT_TYPE.sql
Select 'AL_REF_MATCH_SCORE' from DUAL;
@.\DataImport\AL_REF_MATCH_SCORE.sql
Select 'AUTH_USERROLE_ACCESSCONTROL' from DUAL;
@.\DataImport\AUTH_USERROLE_ACCESSCONTROL.sql
Select 'CONFIG_TXN_REGISTRY' from DUAL;
@.\DataImport\CONFIG_TXN_REGISTRY.sql
Select 'PROPERTY' from DUAL;
@.\DataImport\PROPERTY.sql
Select 'REF_ADDRESS_TYPE' from DUAL;
@.\DataImport\REF_ADDRESS_TYPE.sql
Select 'REF_BILLING_MODE_TYPE' from DUAL;
@.\DataImport\REF_BILLING_MODE_TYPE.sql
Select 'REF_GROUP_TYPE' from DUAL;
@.\DataImport\REF_GROUP_TYPE.sql
Select 'AL_AUTH_ROLES_REGISTRY' from DUAL;
@.\DataImport\AL_AUTH_ROLES_REGISTRY.sql
Select 'AL_BATCH_ENTITY_TO_PROCESS' from DUAL;
@.\DataImport\AL_BATCH_ENTITY_TO_PROCESS.sql
Select 'AL_MATCH_MERGED_LE_ASSOC' from DUAL;
@.\DataImport\AL_MATCH_MERGED_LE_ASSOC.sql
Select 'AL_REF_ASSOC_TYPE' from DUAL;
@.\DataImport\AL_REF_ASSOC_TYPE.sql
Select 'AL_REF_BILLING_MODE_TYPE' from DUAL;
@.\DataImport\AL_REF_BILLING_MODE_TYPE.sql
Select 'AL_REF_CORPORATION_NAME_TYP' from DUAL;
@.\DataImport\AL_REF_CORPORATION_NAME_TYP.sql
Select 'AL_REF_CURRENCY' from DUAL;
@.\DataImport\AL_REF_CURRENCY.sql
Select 'AL_REF_LE_ROLETYPE' from DUAL;
@.\DataImport\AL_REF_LE_ROLETYPE.sql
Select 'AL_REF_LOBTYPE' from DUAL;
@.\DataImport\AL_REF_LOBTYPE.sql
Select 'AL_REF_PREFERENCE_TYPE' from DUAL;
@.\DataImport\AL_REF_PREFERENCE_TYPE.sql
Select 'AL_REF_STATE_PROVINCE' from DUAL;
@.\DataImport\AL_REF_STATE_PROVINCE.sql
Select 'AL_REF_SUFFIX_NAME' from DUAL;
@.\DataImport\AL_REF_SUFFIX_NAME.sql
Select 'AL_REF_TERMINATION_REASON' from DUAL;
@.\DataImport\AL_REF_TERMINATION_REASON.sql
Select 'ENTITY_GROUP_ASSOC' from DUAL;
@.\DataImport\ENTITY_GROUP_ASSOC.sql
Select 'INACTIVE_LE_REGISTRY' from DUAL;
@.\DataImport\INACTIVE_LE_REGISTRY.sql
Select 'LE_SYSTEM_KEYS_REGISTRY' from DUAL;
@.\DataImport\LE_SYSTEM_KEYS_REGISTRY.sql
Select 'PHONE_STANDARDIZED' from DUAL;
@.\DataImport\PHONE_STANDARDIZED.sql
Select 'REF_CORPORATION_TYPE' from DUAL;
@.\DataImport\REF_CORPORATION_TYPE.sql
Select 'REF_GROUP_SUBTYPE' from DUAL;
@.\DataImport\REF_GROUP_SUBTYPE.sql
Select 'REF_IDENTIFICATION_TYPE' from DUAL;
@.\DataImport\REF_IDENTIFICATION_TYPE.sql
Select 'REF_PREFERENCE_TYPE' from DUAL;
@.\DataImport\REF_PREFERENCE_TYPE.sql
Select 'REF_STATE_PROVINCE' from DUAL;
@.\DataImport\REF_STATE_PROVINCE.sql
Select 'REF_TERMINATION_REASON' from DUAL;
@.\DataImport\REF_TERMINATION_REASON.sql
Select 'AL_ACCOUNT' from DUAL;
@.\DataImport\AL_ACCOUNT.sql
Select 'AL_CONFIG_LANGUAGE_CODE' from DUAL;
@.\DataImport\AL_CONFIG_LANGUAGE_CODE.sql
Select 'AL_INACTIVE_LE_REGISTRY' from DUAL;
@.\DataImport\AL_INACTIVE_LE_REGISTRY.sql
Select 'AL_LE_ACCOUNT_ASSOC' from DUAL;
@.\DataImport\AL_LE_ACCOUNT_ASSOC.sql
Select 'AL_REF_ACCOUNT_MDM_STATUS' from DUAL;
@.\DataImport\AL_REF_ACCOUNT_MDM_STATUS.sql
Select 'AL_REF_AGREEMENT_TYPE' from DUAL;
@.\DataImport\AL_REF_AGREEMENT_TYPE.sql
Select 'AL_REF_CORPORATION_NAME_TYPE' from DUAL;
@.\DataImport\AL_REF_CORPORATION_NAME_TYPE.sql
Select 'AL_REF_GROUP_SUBTYPE' from DUAL;
@.\DataImport\AL_REF_GROUP_SUBTYPE.sql
Select 'AL_REF_LE_RATING' from DUAL;
@.\DataImport\AL_REF_LE_RATING.sql
Select 'AL_REF_MATCH_PROPOSED_ACTION' from DUAL;
@.\DataImport\AL_REF_MATCH_PROPOSED_ACTION.sql
Select 'AL_REF_MATCH_RESULT' from DUAL;
@.\DataImport\AL_REF_MATCH_RESULT.sql
Select 'AL_REF_PROPERTY_LE_RELTYPE' from DUAL;
@.\DataImport\AL_REF_PROPERTY_LE_RELTYPE.sql
Select 'CONFIG_APP_PROPERTIES' from DUAL;
@.\DataImport\CONFIG_APP_PROPERTIES.sql
Select 'REF_ACCOUNT_MDM_STATUS' from DUAL;
@.\DataImport\REF_ACCOUNT_MDM_STATUS.sql
Select 'REF_ADDRESS_SUBTYPE' from DUAL;
@.\DataImport\REF_ADDRESS_SUBTYPE.sql
Select 'REF_ASSOC_TYPE' from DUAL;
@.\DataImport\REF_ASSOC_TYPE.sql
Select 'REF_HIGHEST_EDU_QUAL' from DUAL;
@.\DataImport\REF_HIGHEST_EDU_QUAL.sql
Select 'REF_MATCH_ACTIONSTATUS' from DUAL;
@.\DataImport\REF_MATCH_ACTIONSTATUS.sql
Select 'REF_MATCH_PROPOSED_ACTION' from DUAL;
@.\DataImport\REF_MATCH_PROPOSED_ACTION.sql
Select 'REF_PHONE_TYPE' from DUAL;
@.\DataImport\REF_PHONE_TYPE.sql
Select 'AL_AUTH_USER_ROLE_ASSOC' from DUAL;
@.\DataImport\AL_AUTH_USER_ROLE_ASSOC.sql
Select 'AL_CONFIG_TXN_REGISTRY' from DUAL;
@.\DataImport\AL_CONFIG_TXN_REGISTRY.sql
Select 'AL_MATCH_CANDIDATE_LE_REGISTRY' from DUAL;
@.\DataImport\AL_MATCH_CANDIDATE_LE_REGISTRY.sql
Select 'AL_REF_IDENTIFICATION_TYPE' from DUAL;
@.\DataImport\AL_REF_IDENTIFICATION_TYPE.sql
Select 'AL_REF_LANGUAGE_CODE' from DUAL;
@.\DataImport\AL_REF_LANGUAGE_CODE.sql
Select 'AL_REF_LE_RELATIONSHIP_TYPE' from DUAL;
@.\DataImport\AL_REF_LE_RELATIONSHIP_TYPE.sql
Select 'AL_REF_MATCH_ACTIONSTATUS' from DUAL;
@.\DataImport\AL_REF_MATCH_ACTIONSTATUS.sql
Select 'AL_REF_MATCH_THRESHOLD' from DUAL;
@.\DataImport\AL_REF_MATCH_THRESHOLD.sql
Select 'AL_REF_PREFIX_NAME' from DUAL;
@.\DataImport\AL_REF_PREFIX_NAME.sql
Select 'CONFIG_ERRORCODE_REGISTRY' from DUAL;
@.\DataImport\CONFIG_ERRORCODE_REGISTRY.sql
Select 'CONFIG_INQUIRY_LEVELS' from DUAL;
@.\DataImport\CONFIG_INQUIRY_LEVELS.sql
Select 'ENTITY_GROUP' from DUAL;
@.\DataImport\ENTITY_GROUP.sql
Select 'LE_ADDRESS_ASSOC' from DUAL;
@.\DataImport\LE_ADDRESS_ASSOC.sql
Select 'MATCH_CANDIDATE_LE_REGISTRY' from DUAL;
@.\DataImport\MATCH_CANDIDATE_LE_REGISTRY.sql
Select 'REF_ACCOUNT_SOURCE_STATUS' from DUAL;
@.\DataImport\REF_ACCOUNT_SOURCE_STATUS.sql
Select 'REF_CURRENCY' from DUAL;
@.\DataImport\REF_CURRENCY.sql
Select 'REF_ENTITY_OBJECT_TYPE' from DUAL;
@.\DataImport\REF_ENTITY_OBJECT_TYPE.sql
Select 'REF_LE_RELATIONSHIP_TYPE' from DUAL;
@.\DataImport\REF_LE_RELATIONSHIP_TYPE.sql
Select 'REF_MATCH_THRESHOLD' from DUAL;
@.\DataImport\REF_MATCH_THRESHOLD.sql
Select 'REF_MERGE_REASON' from DUAL;
@.\DataImport\REF_MERGE_REASON.sql
Select 'REF_PERSONNAME_TYPE' from DUAL;
@.\DataImport\REF_PERSONNAME_TYPE.sql
Select 'REF_PREFIX_NAME' from DUAL;
@.\DataImport\REF_PREFIX_NAME.sql
Select 'REF_SOURCE_SYSTEM' from DUAL;
@.\DataImport\REF_SOURCE_SYSTEM.sql
Select 'AL_ENTITY_GROUP_ASSOC' from DUAL;
@.\DataImport\AL_ENTITY_GROUP_ASSOC.sql
Select 'AL_LE_PREFERENCES' from DUAL;
@.\DataImport\AL_LE_PREFERENCES.sql
Select 'AL_LE_PROPERTY_ASSOC' from DUAL;
@.\DataImport\AL_LE_PROPERTY_ASSOC.sql
Select 'AL_LE_SYSTEM_KEYS_REGISTRY' from DUAL;
@.\DataImport\AL_LE_SYSTEM_KEYS_REGISTRY.sql
Select 'AL_REF_BATCH_ACTION_STATUS' from DUAL;
@.\DataImport\AL_REF_BATCH_ACTION_STATUS.sql
Select 'AL_REF_BATCH_PROPOSED_ACTION' from DUAL;
@.\DataImport\AL_REF_BATCH_PROPOSED_ACTION.sql
Select 'AL_REF_GENDER' from DUAL;
@.\DataImport\AL_REF_GENDER.sql
Select 'AL_REF_STATUS_IN_SOURCE' from DUAL;
@.\DataImport\AL_REF_STATUS_IN_SOURCE.sql
Select 'AUTH_USER_REGISTRY' from DUAL;
@.\DataImport\AUTH_USER_REGISTRY.sql
Select 'CONFIG_LANGUAGE_CODE' from DUAL;
@.\DataImport\CONFIG_LANGUAGE_CODE.sql
Select 'LE_ACCOUNT_ASSOC' from DUAL;
@.\DataImport\LE_ACCOUNT_ASSOC.sql
Select 'LE_PROPERTY_ASSOC' from DUAL;
@.\DataImport\LE_PROPERTY_ASSOC.sql
Select 'MATCH_MERGED_LE_ASSOC' from DUAL;
@.\DataImport\MATCH_MERGED_LE_ASSOC.sql
Select 'MISCELLANEOUS_INFO' from DUAL;
@.\DataImport\MISCELLANEOUS_INFO.sql
Select 'REF_CORPORATION_NAME_TYPE' from DUAL;
@.\DataImport\REF_CORPORATION_NAME_TYPE.sql
Select 'REF_GENDER' from DUAL;
@.\DataImport\REF_GENDER.sql
Select 'REF_LOBTYPE' from DUAL;
@.\DataImport\REF_LOBTYPE.sql
Select 'REF_PHONE_SUBTYPE' from DUAL;
@.\DataImport\REF_PHONE_SUBTYPE.sql
Select 'ACCOUNT_ADDRESS_ASSOC' from DUAL;
@.\DataImport\ACCOUNT_ADDRESS_ASSOC.sql
Select 'AL_ACCOUNT_ADDRESS_ASSOC' from DUAL;
@.\DataImport\AL_ACCOUNT_ADDRESS_ASSOC.sql
Select 'AL_ADDRESS' from DUAL;
@.\DataImport\AL_ADDRESS.sql
Select 'AL_CONFIG_ERRORCODE_REGISTRY' from DUAL;
@.\DataImport\AL_CONFIG_ERRORCODE_REGISTRY.sql
Select 'AL_LE_ADDRESS_ASSOC' from DUAL;
@.\DataImport\AL_LE_ADDRESS_ASSOC.sql
Select 'AL_LE_IDENTIFIER_KYC_REGISTRY' from DUAL;
@.\DataImport\AL_LE_IDENTIFIER_KYC_REGISTRY.sql
Select 'AL_LE_TO_LE_RELATIONSHIP' from DUAL;
@.\DataImport\AL_LE_TO_LE_RELATIONSHIP.sql
Select 'AL_LE_VEHICLE_ASSOC' from DUAL;
@.\DataImport\AL_LE_VEHICLE_ASSOC.sql
Select 'AL_PHONE_STANDARDIZED' from DUAL;
@.\DataImport\AL_PHONE_STANDARDIZED.sql
Select 'AL_REF_ADDRESS_SUBTYPE' from DUAL;
@.\DataImport\AL_REF_ADDRESS_SUBTYPE.sql
Select 'AL_REF_ADDRESS_TYPE' from DUAL;
@.\DataImport\AL_REF_ADDRESS_TYPE.sql
Select 'AL_REF_CORPORATION_TYPE' from DUAL;
@.\DataImport\AL_REF_CORPORATION_TYPE.sql
Select 'AL_REF_GROUP_TYPE' from DUAL;
@.\DataImport\AL_REF_GROUP_TYPE.sql
Select 'AL_REF_MERGE_REASON' from DUAL;
@.\DataImport\AL_REF_MERGE_REASON.sql
Select 'AL_REF_PERSONNAME_TYPE' from DUAL;
@.\DataImport\AL_REF_PERSONNAME_TYPE.sql
Select 'AL_REF_PERSON_TYPE' from DUAL;
@.\DataImport\AL_REF_PERSON_TYPE.sql
Select 'AL_REF_STATUS_TYPE' from DUAL;
@.\DataImport\AL_REF_STATUS_TYPE.sql
Select 'BATCH_ENTITY_TO_PROCESS' from DUAL;
@.\DataImport\BATCH_ENTITY_TO_PROCESS.sql
Select 'LEGALENTITY' from DUAL;
@.\DataImport\LEGALENTITY.sql
Select 'LE_TO_LE_RELATIONSHIP' from DUAL;
@.\DataImport\LE_TO_LE_RELATIONSHIP.sql
Select 'PERSONNAMES' from DUAL;
@.\DataImport\PERSONNAMES.sql
Select 'REF_AGREEMENT_TYPE' from DUAL;
@.\DataImport\REF_AGREEMENT_TYPE.sql
Select 'REF_INACTIVATION_REASON' from DUAL;
@.\DataImport\REF_INACTIVATION_REASON.sql
Select 'REF_INDUSTRY_CODE' from DUAL;
@.\DataImport\REF_INDUSTRY_CODE.sql
Select 'REF_LE_RATING' from DUAL;
@.\DataImport\REF_LE_RATING.sql
Select 'REF_MATCH_SCORE' from DUAL;
@.\DataImport\REF_MATCH_SCORE.sql
Select 'REF_PERSON_TYPE' from DUAL;
@.\DataImport\REF_PERSON_TYPE.sql
Select 'REF_RELATIONSHIP_STATUS' from DUAL;
@.\DataImport\REF_RELATIONSHIP_STATUS.sql
Select 'VEHICLE' from DUAL;
@.\DataImport\VEHICLE.sql
Select 'ACCOUNT_PHONE_ASSOC' from DUAL;
@.\DataImport\ACCOUNT_PHONE_ASSOC.sql
Select 'ADDRESS' from DUAL;
@.\DataImport\ADDRESS.sql
Select 'AL_ACCOUNT_PHONE_ASSOC' from DUAL;
@.\DataImport\AL_ACCOUNT_PHONE_ASSOC.sql
Select 'AL_AUTH_USERROLE_ACCESSCONTROL' from DUAL;
@.\DataImport\AL_AUTH_USERROLE_ACCESSCONTROL.sql
Select 'AL_LEGALENTITY' from DUAL;
@.\DataImport\AL_LEGALENTITY.sql
Select 'AL_LE_PERSON' from DUAL;
@.\DataImport\AL_LE_PERSON.sql
Select 'AL_PERSONNAMES' from DUAL;
@.\DataImport\AL_PERSONNAMES.sql
Select 'AL_PROPERTY' from DUAL;
@.\DataImport\AL_PROPERTY.sql
Select 'AL_REF_ACCOUNT_SOURCE_STATUS' from DUAL;
@.\DataImport\AL_REF_ACCOUNT_SOURCE_STATUS.sql
Select 'AL_REF_BRANCH_CODE' from DUAL;
@.\DataImport\AL_REF_BRANCH_CODE.sql
Select 'AL_REF_COUNTRY_ISO' from DUAL;
@.\DataImport\AL_REF_COUNTRY_ISO.sql
Select 'AL_REF_DEACTIVATION_REASON' from DUAL;
@.\DataImport\AL_REF_DEACTIVATION_REASON.sql
Select 'AL_REF_INACTIVATION_REASON' from DUAL;
@.\DataImport\AL_REF_INACTIVATION_REASON.sql
Select 'AL_REF_PHONE_SUBTYPE' from DUAL;
@.\DataImport\AL_REF_PHONE_SUBTYPE.sql
Select 'AL_REF_SOURCE_SYSTEM' from DUAL;
@.\DataImport\AL_REF_SOURCE_SYSTEM.sql
Select 'AL_VEHICLE' from DUAL;
@.\DataImport\AL_VEHICLE.sql
Select 'AUTH_USER_ROLE_ASSOC' from DUAL;
@.\DataImport\AUTH_USER_ROLE_ASSOC.sql
Select 'CORPORATIONNAMES' from DUAL;
@.\DataImport\CORPORATIONNAMES.sql
Select 'LE_IDENTIFIER_KYC_REGISTRY' from DUAL;
@.\DataImport\LE_IDENTIFIER_KYC_REGISTRY.sql
Select 'LE_PHONE_ASSOC' from DUAL;
@.\DataImport\LE_PHONE_ASSOC.sql
Select 'LE_PREFERENCES' from DUAL;
@.\DataImport\LE_PREFERENCES.sql
Select 'LE_VEHICLE_ASSOC' from DUAL;
@.\DataImport\LE_VEHICLE_ASSOC.sql
Select 'REF_BATCH_PROPOSED_ACTION' from DUAL;
@.\DataImport\REF_BATCH_PROPOSED_ACTION.sql
Select 'REF_CLASSIFICATION_CODE' from DUAL;
@.\DataImport\REF_CLASSIFICATION_CODE.sql
Select 'REF_LANGUAGE_CODE' from DUAL;
@.\DataImport\REF_LANGUAGE_CODE.sql
Select 'REF_LE_ROLETYPE' from DUAL;
@.\DataImport\REF_LE_ROLETYPE.sql
Select 'REF_STATUS_IN_SOURCE' from DUAL;
@.\DataImport\REF_STATUS_IN_SOURCE.sql
Select 'REF_STATUS_TYPE' from DUAL;
@.\DataImport\REF_STATUS_TYPE.sql

COMMIT;