package com.yugandhar.mdm.match.rules;

public final class YugandharMatchingConstants {

	public static String PERSON_BLOCK_NAME = "PERSON.BLOCK.NAME";
	public static String PERSON_BLOCK_ADDRESS = "PERSON.BLOCK.ADDRESS";
	public static String PERSON_ATTR_GENDER = "PERSON.ATTR.GENDER";
	public static String PERSON_BLOCK_IDENTIFIER_KYC = "PERSON.BLOCK.IDENTIFIER_KYC";
	public static String PERSON_ATTR_DOB = "PERSON.ATTR.DOB";
	public static String PERSON_BLOCK_PHONE = "PERSON.BLOCK.PHONE";
	public static String CORPORATION_BLOCK_IDENTIFIER_KYC = "CORPORATION.BLOCK.IDENTIFIER_KYC";
	public static String CORPORATION_ATTR_NAME = "CORPORATION.ATTR.NAME";
	public static String CORPORATION_BLOCK_ADDRESS = "CORPORATION.BLOCK.ADDRESS";
	public static String CORPORATION_ATTR_PHONE = "CORPORATION.ATTR.PHONE";
	public static String PERSON_ATTR_NAMEONE = "PERSON.ATTR.NAMEONE";
	public static String PERSON_ATTR_NAMETWO = "PERSON.ATTR.NAMETWO";
	public static String PERSON_ATTR_LASTNAME = "PERSON.ATTR.LASTNAME";
	public static String ADDRESS_ATTR_ADDRESS_LINE_ONE = "ADDRESS.ATTR.ADDRESS_LINE_ONE";
	public static String ADDRESS_ATTR_ADDRESS_LINE_TWO = "ADDRESS.ATTR.ADDRESS_LINE_TWO";
	public static String ADDRESS_ATTR_ADDRESS_LINE_THREE = "ADDRESS.ATTR.ADDRESS_LINE_THREE";
	public static String ADDRESS_ATTR_ADDRESS_LINE_FOUR = "ADDRESS.ATTR.ADDRESS_LINE_FOUR";
	public static String ADDRESS_ATTR_STREET_NAME = "ADDRESS.ATTR.STREET_NAME";
	public static String ADDRESS_ATTR_CITY = "ADDRESS.ATTR.CITY";
	public static String ADDRESS_ATTR_COUNTRY_REFKEY = "ADDRESS.ATTR.COUNTRY_REFKEY";
	public static String ADDRESS_ATTR_POSTAL_CODE = "ADDRESS.ATTR.POSTAL_CODE";
	
	//for REF_MATCH_SCORE table
	public static String  MATCH_ENTITY_OBJECT_NAME_PERSON = "PERSON";
	public static String  MATCH_ENTITY_OBJECT_NAME_CORPORATION = "CORPORATION";
	public static String  MATCH_ENTITY_OBJECT_NAME_ADDRESS = "ADDRESS";
}
