use yug_owner;
/* data table ddl*/
CREATE TABLE FACILITYDEMO(
`ID_PK` VARCHAR(50) NOT NULL,
`VERSION` DECIMAL(22,0) NOT NULL,
`CREATED_TS` DATETIME(6) NOT NULL,
`DELETED_TS` DATETIME(6) NULL DEFAULT NULL,
`UPDATED_TS` DATETIME(6) NOT NULL,
`UPDATED_BY_USER` VARCHAR(50) NOT NULL ,
`UPDATED_BY_TXN_ID` VARCHAR(100) NULL DEFAULT NULL ,
`FACILITY_NAME` VARCHAR(100) NOT NULL ,
`LOCATION` VARCHAR(150) NULL DEFAULT NULL ,
PRIMARY KEY (`ID_PK`)
)
ENGINE=InnoDB
;

/* Audit log table ddl for base data table. This table stores the audit log history*/
CREATE TABLE AL_FACILITYDEMO(
`AUDITLOG_ID_PK` varchar(50) NOT NULL,
`AUDITLOG_CREATED_TS` datetime(6) NOT NULL,
`AUDITLOG_ACTION_CODE` varchar(1) NOT NULL,
`ID_PK` VARCHAR(50) NOT NULL,
`VERSION` DECIMAL(22,0) NOT NULL,
`CREATED_TS` DATETIME(6) NOT NULL,
`DELETED_TS` DATETIME(6) NULL DEFAULT NULL,
`UPDATED_TS` DATETIME(6) NOT NULL,
`UPDATED_BY_USER` VARCHAR(50) NOT NULL ,
`UPDATED_BY_TXN_ID` VARCHAR(100) NULL DEFAULT NULL ,
`FACILITY_NAME` VARCHAR(100) NOT NULL ,
`LOCATION` VARCHAR(150) NULL DEFAULT NULL ,
PRIMARY KEY (`AUDITLOG_ID_PK`)
)
ENGINE=InnoDB
;

/* Audit log triggers which will make entries in the AL_FACILITYDEMO table whenever FACILITYDEMO table is updated*/
DELIMITER //
CREATE TRIGGER `D_FACILITYDEMO` AFTER DELETE ON `FACILITYDEMO` FOR EACH ROW BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'D',  OLD.ID_PK,  OLD.VERSION,  OLD.CREATED_TS,  OLD.DELETED_TS,  OLD.UPDATED_TS,  OLD.UPDATED_BY_USER,  OLD.UPDATED_BY_TXN_ID,  OLD.FACILITY_NAME,  OLD.LOCATION); END//
CREATE TRIGGER `I_FACILITYDEMO` AFTER INSERT ON `FACILITYDEMO` FOR EACH ROW BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'I', NEW.ID_PK, NEW.VERSION, NEW.CREATED_TS, NEW.DELETED_TS, NEW.UPDATED_TS, NEW.UPDATED_BY_USER, NEW.UPDATED_BY_TXN_ID, NEW.FACILITY_NAME, NEW.LOCATION); END//
CREATE TRIGGER `U_FACILITYDEMO` AFTER UPDATE ON `FACILITYDEMO` FOR EACH ROW BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'U', NEW.ID_PK, NEW.VERSION, NEW.CREATED_TS, NEW.DELETED_TS, NEW.UPDATED_TS, NEW.UPDATED_BY_USER, NEW.UPDATED_BY_TXN_ID, NEW.FACILITY_NAME, NEW.LOCATION); END//

/*Rollback scripts
DROP TRIGGER `D_FACILITYDEMO`;
DROP TRIGGER `I_FACILITYDEMO`;
DROP TRIGGER `U_FACILITYDEMO`;
DROP table FACILITYDEMO;
drop table AL_FACILITYDEMO;
*/

DELIMITER ;
CREATE TABLE `ref_color` (
	`ID_PK` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`VERSION` DECIMAL(22,0) NOT NULL,
	`CREATED_TS` DATETIME(6) NOT NULL,
	`DELETED_TS` DATETIME(6) NULL DEFAULT NULL,
	`UPDATED_TS` DATETIME(6) NOT NULL,
	`UPDATED_BY_USER` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`UPDATED_BY_TXN_ID` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CONFIG_LANGUAGE_CODE_KEY` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`KEY` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`VALUE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`DESCRIPTION` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`ID_PK`),
	UNIQUE INDEX `REF_LANGUAGE_CODE_UNIQUEKEY` (`KEY`, `CONFIG_LANGUAGE_CODE_KEY`),
	INDEX `INDX_REF_COLOR_1` (`KEY`),
	INDEX `INDX_REF_COLOR_2` (`VALUE`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;


CREATE TABLE `al_ref_color` (
	`AUDITLOG_ID_PK` varchar(50) NOT NULL,
	`AUDITLOG_CREATED_TS` datetime(6) NOT NULL,
	`AUDITLOG_ACTION_CODE` varchar(1) NOT NULL,
	`ID_PK` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`VERSION` DECIMAL(22,0) NOT NULL,
	`CREATED_TS` DATETIME(6) NOT NULL,
	`DELETED_TS` DATETIME(6) NULL DEFAULT NULL,
	`UPDATED_TS` DATETIME(6) NOT NULL,
	`UPDATED_BY_USER` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`UPDATED_BY_TXN_ID` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`CONFIG_LANGUAGE_CODE_KEY` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	`KEY` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`VALUE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`DESCRIPTION` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`AUDITLOG_ID_PK`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;

/* Audit log triggers which will make entries in the al_ref_color table whenever ref_color table is updated*/
DELIMITER //
CREATE TRIGGER `U_ref_color` AFTER UPDATE ON `ref_color` FOR EACH ROW  
BEGIN INSERT INTO al_ref_color ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, `KEY`, VALUE, DESCRIPTION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'I', NEW.ID_PK, NEW.VERSION, NEW.CREATED_TS, NEW.DELETED_TS, NEW.UPDATED_TS, NEW.UPDATED_BY_USER, NEW.UPDATED_BY_TXN_ID, NEW.CONFIG_LANGUAGE_CODE_KEY, NEW.KEY, NEW.VALUE, NEW.DESCRIPTION); END//

CREATE TRIGGER `I_ref_color` AFTER INSERT ON `ref_color` FOR EACH ROW  
BEGIN INSERT INTO al_ref_color ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, `KEY`, VALUE, DESCRIPTION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'U', NEW.ID_PK, NEW.VERSION, NEW.CREATED_TS, NEW.DELETED_TS, NEW.UPDATED_TS, NEW.UPDATED_BY_USER, NEW.UPDATED_BY_TXN_ID, NEW.CONFIG_LANGUAGE_CODE_KEY, NEW.KEY, NEW.VALUE, NEW.DESCRIPTION); END//

CREATE TRIGGER `D_ref_color` AFTER DELETE ON `ref_color` FOR EACH ROW  
BEGIN INSERT INTO al_ref_color ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, `KEY`, VALUE, DESCRIPTION ) VALUES( uuid(), CURRENT_TIMESTAMP(6) , 'D',  OLD.ID_PK,  OLD.VERSION,  OLD.CREATED_TS,  OLD.DELETED_TS,  OLD.UPDATED_TS,  OLD.UPDATED_BY_USER,  OLD.UPDATED_BY_TXN_ID,  OLD.CONFIG_LANGUAGE_CODE_KEY,  OLD.KEY,  OLD.VALUE,  OLD.DESCRIPTION); END//

/*Rollback scripts
DROP TRIGGER `D_ref_color`;
DROP TRIGGER `I_ref_color`;
DROP TRIGGER `U_ref_color`;
DROP table al_ref_color;
drop table ref_color;
*/

